### ISSUE TITLE
plugins add / install should consider only release versions by default

### ISSUE THREAD

**Issue by petrem** [Encapsia/encapsia-cli#109]
When using `encapsia plugins add` or `encapsia plugins install`, development versions/builds should not be considered "latest", by default. This would also mean `encapsia plugins install entry-2.1` should select latest 2.1.x release version.

To be considered if we fix this or jump to a more comprehensive change of how we allow versions to be specified (see https://github.com/Encapsia/encapsia-cli/issues/93 but it doesn't say much at this time).

**Comment by mpopetcmed** [comment]
To clarify certain aspects of the requirements:

* Semver goes like this `MAJOR.MINOR.PATCH-PREREREASE+BUILD`

* By development versions I understand the ones that have a pre-release label (e.g.: `2.1.0-rc1`, `5.0.1-candidate+b20230206`)
* If there is no pre-release label, but there is a build label - we consider that a release version (e.g. `3.3.0+b20230207`)

1. `encapsia plugins install` lists all the existing plugin packages in the local plugins store - and it might contain prerelease versions of the plugins. Those will be ignored when selecting source candidates
2. `encapsia plugins add` searches the S3 bucket(s) for source plugins - I don't think there will be any prerelease versions there - should we filter those out, just in case?

**Comment by petrem** [comment]
> By development versions I understand the ones that have a pre-release label

Indeed.

> if there is no pre-release label, but there is a build label - we consider that a release version

That is the meaning indeed under SemVer, but I'm not sure it is a good idea. If nothing else, which out of many would the tool choose?

Potential approaches would be, I think:
* Ignore any packages with a build label (do we have any?), as they wouldn't exist. A bit better: ignore them, but warn the user of their existence and that we don't use them.
* If there is exactly one package (at a version) with a build label, and none without it, use that package. Otherwise, issue an error (in add/install) or warning (when listing).

Anything else that would make sense?

> Those will be ignored when selecting source candidates

By default. We need a way to install those too. Yes, another option! :) I propose `--pre`.
Also if the user specifies an exact candidate (e.g. `encapsia plugins install foo-1.2.3-a.5`, that will be used regardless.

> encapsia plugins add searches the S3 bucket(s) for source plugins - I don't think there will be any prerelease versions there - should we filter those out, just in case?

There are prerelease versions there already, and that is why this bug was raised. I *think* the same rules should apply (i.e. download prereleases only if explicitly named or allowed with `--pre`).

**Comment by petrem** [comment]
Reminder (from off-line discussion): `--latest-existing` and `--all-available` would ideally match the new behaviour (if it makes sense, I don't exactly remember what they do).

**Comment by mpopetcmed** [comment]
`--all-available` is a mess right now, it will download all the versions of all the plugins, not just the latest ones (for both `add` and `install`)

**Comment by petrem** [comment]
I thought that was its intention, @mpopetcmed ?
