### ISSUE TITLE
Setting --include-prereleases flag in config file

### ISSUE THREAD

**Issue by RattyBiscuit** [Encapsia/encapsia-cli#121]
When working on developing Insight plugins my team and I will more regularly need to install the development versions of plugins, which now requires the additional `--pre` or `--include-prereleases` flag

To improve our workflow it would be great if we could set a default value in the `~/.encapsia/config.toml` file allowing us to always include pre-releases on our machines

**Comment by petrem** [comment]
Please reopen if it doesn't work for you, but it should.
