### ISSUE TITLE
Create "plugins reactor" subcommand

### ISSUE THREAD

**Issue by tcorbettclark** [Encapsia/encapsia-cli#17]
E.g. forward local calls to remote for even easier dev without installing anything except the SQL.

**Comment by tcorbettclark** [comment]
E.g. forward local calls to remote for even easier dev without installing anything except the SQL.

**Comment by petrem** [comment]
This is a bit vague. Please either explain it further, or let's close it.

**Comment by petrem** [comment]
Won't do. Closing.
