### ISSUE TITLE
To use 'encapsia plugins install' without confirmation you need to use --force; Maybe create a -y for click.confirm?

### ISSUE THREAD

**Issue by adiniscmed** [Encapsia/encapsia-cli#52]

**Comment by petrem** [comment]
What's your usecase?

**Comment by adiniscmed** [comment]
There are two cases where this would be usefull:

One is on upgrading a set of plugins on several servers with a script/automated or even manually, it prompts for Y (user input) on each run. If using --force, it will reinstall the already installed plugins.

The second one is on initial plugin install on a server/system, where you want to install all plugins for the first time with a script/automated, and it prompts for Y (user input) (this actually can be solved using --force, but is used inappropriately)

**Comment by petrem** [comment]
Ok, so I assume this would be something like `--assume-yes`, meaning "Do not prompt on sane requests" rather than the "Shut up and break my system" of `--force`.

How do you feel about downgrades? I'd rather not automatically do those with this new flag.

**Comment by petrem** [comment]
Confirmation dialogues 
===================

There are multiple confirmation prompts in other places, described in the table below.
The line numbers are valid with the current `master`, at commit 9c31728d89271b44d5bfee7088b3883ac74df000.

Potentially problematic situations, where the action might not be what the user intended when issuing `--force`, are highlighted (see more below).

| File | Command | Actions confirmed by prompt |
| --- | --- | --- |
| plugins.py:393 | install | install new plugin; **downgrade plugin**; upgrade plugin; **reinstall plugin** |
| plugins.py:437| uninstall | uninstall new plugin |
| plugins.py:576| dev-destroy | destroy (plugin) namespace(s) |
| database.py:38 | restore | restore from backup |
| fixtures.py:47 | use | use fixture |
| fixtures.py:64 | delete | delete (existing) fixture |

Except where highlighted, `--force` "means" `--yes|--assume-yes`, quite naturally. The name of the option, `--force`, is, possibly, well, forced.

Issues
---------

There are two distinct issues with `--force` for `plugins install`: 
* It will reinstall existing plugins. This is useless and undesirable *most of the time*, but we need to be able to perform reinstall.
* It will happily downgrade plugins. This may be surprising and not what the user desired but of course we need to be able to perform the action.

Proposed new options and changes
=============================

A compromise could be to keep the existing `--force` with the same meaning (and mark it *deprecated*), and add new options with more concise meaning:

| Command | Option | Meaning |
| --- | --- | --- |
| `plugins install` | `--yes` | Do not prompt for confirmation. This will not automatically downgrade or reinstall. |
| `plugins install`| `--reinstall` | Change default behaviour to never reinstall by default. With this option, selected plugins would be reinstalled. |
| `plugins install`| `--downgrade` | Change default behaviour to never downgrade by default. With this option, selected plugins would be downgraded. |
| `plugins install`| `--force` | Do not prompt for confirmation, reinstall and downgrade. Same as `--yes --reinstall --downgrade`. |
| `plugins dev-destroy` | `--yes` \| `--force` | Do not prompt for confirmation.|
| `database restore` | `--yes` \| `--force` | Do not prompt for confirmation.|
| `fixtures use` | `--yes` \| `--force` | Do not prompt for confirmation.|
| `fixtures delete`| `--yes` \| `--force` | Do not prompt for confirmation.|

[Implementation detail] Deprecating `--force` could be done e.g. as described in https://stackoverflow.com/a/50402799/3540204 . Or wait for https://github.com/pallets/click/issues/2263 ...

**Comment by rosselliott** [comment]
+1 to ```--yes```,  ```--reinstall```,  and ```--downgrade```.
Anything to get us to pay more attention to what we are installing.
Is there any Sys Ops tooling that needs to change to take account of this or does it check desired plugin versions and install as needed?

**Comment by petrem** [comment]
Sys ops state that they are not using encapsia-cli anymore, or at least not in their toolchain.

**Comment by mpopetcmed** [comment]
If we intend to deprecate --force, we should provide an alternative CL option.
These are the `plugin` subcommands that are currently using `--force`, please provide option names for the cases where there is no suggested replacement. 

(if suggested option is in **bold**, it was taken from Petre's previous suggestions)

|Subcommand  |Context |Suggested option|
|-------------|----------------------|-------------------
|`install`    | _add_to_local_store_from_s3 <=> overwrite if file already exists in local store | ? |
|             | create_install_plan => reinstall if same version | **`--reinstall`** |
|             | create_install_plan => downgrade if older version | **`--downgrade`** |
|             | do not prompt for confirmation                    | **`--yes`**  |
|`uninstall`  | do not prompt for confirmation                    | `--yes`  |
|`dev_update` | _get_modified_plugin_directories                  | ?      |
|`dev_destroy`| do not prompt for confirmation                    | **`--yes`**  |
|`dev_build`  | overwrite existing plugin file in local store     | ?      |
|`add`        | _download_plugins_from_s3 + _add_to_local_store_from_uri => overwrite if file already exists in local store | ?|
