### ISSUE TITLE
make encapsia plugins status output less wide

### ISSUE THREAD

**Issue by petrem** [Encapsia/encapsia-cli#63]
`encapsia plugins status` output width does not fit a normal terminal's columns. Most of the time we care about 'name' and 'version' only, maybe 'available' too.
Consider adding a --verbose (or --full) flag and limit the number of columns by default.

**Comment by mpopetcmed** [comment]
currently there's a `--long` flag for the `status` command, that adds _plugin_tags_ and _description_ to the default _name_, _version_, _available_ and _installed_ columns

do you think it is ok to move _installed_ and maybe _available_ under `--long`, or add another flag for finer control?

**Comment by petrem** [comment]
Yes, it looks good enough as it is now (fits in a normal terminal window). I'll close it.
