### ISSUE TITLE
Error if "variant" is specified in encapsia plugin uninstall 

### ISSUE THREAD

**Issue by dconstantinescu** [Encapsia/encapsia-cli#78]
dconstantinescu@inf1:~/inf-systems/production/Sponsor/trial-name$ encapsia --host trial-name-01.encapsia.com plugins uninstall "shared_trial_settings-variant-trial-name"
Preparing to uninstall: shared_trial_settings-variant-trial-name
Are you sure? [y/N]: y
Calling: api.run_task(pluginsmanager, icepluginsmanager.uninstall_plugin) (attempt 1/10)
Uninstalling shared_trial_settings-variant-trial-name...Done
Status: error
Manifest for shared_trial_settings-variant-trial-name not found. Not installed?
Could not determine installed plugin_id for shared_trial_settings-variant-trial-name. Giving up.
Aborting...

dconstantinescu@inf1:~/inf-systems/production/Sponsor/trial-name$ encapsia --host trial-name-01.encapsia.com plugins uninstall "shared_trial_settings"
Preparing to uninstall: shared_trial_settings
Are you sure? [y/N]: y
Calling: api.run_task(pluginsmanager, icepluginsmanager.uninstall_plugin) (attempt 1/10)
Uninstalling shared_trial_settings...............Done

**Comment by petrem** [comment]
There cannot be more than one variant installed at a time, so there is no need for uninstall to take a variant extension. However, the tool performs an erroneous API call to encapsia right now, which is a bug of course.

There could be at least three ways to address this:
1. Display an error asking the user to not include the `-variant-*` part.
2. Ignore the variant extension and issue the correct API request.
3. Verify the variant against the one installed, and issue (the correct API request) only if there is a match.

**Comment by petrem** [comment]
fixed in #105
